# Generated by Django 4.0.5 on 2022-06-23 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0002_product'),
        ('alpha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='beta.product'),
        ),
    ]
